SELECT INFO.ITEM_ID,
       INFO.ITEM_NAME
FROM ITEM_INFO AS INFO
INNER JOIN ITEM_TREE AS TREE -- ITEM_ID를 외래키로 조인해서 모든 아이템에 PARENT_ITEM_ID를 붙인다
    ON INFO.ITEM_ID = TREE.ITEM_ID
WHERE TREE.PARENT_ITEM_ID IS NULL -- PARENT_ITEM_ID 가 NULL 인 것만 