SELECT E.ID
FROM ECOLI_DATA AS E
LEFT JOIN ECOLI_DATA AS P
    ON E.PARENT_ID = P.ID
LEFT JOIN ECOLI_DATA AS PP
    ON P.PARENT_ID = PP.ID
WHERE P.PARENT_ID IS NOT NULL
    AND PP.PARENT_ID IS NULL
ORDER BY E.ID ASC
