SELECT YEAR(SALES_DATE) AS YEAR,
       MONTH(SALES_DATE) AS MONTH,
       GENDER,
       COUNT(DISTINCT USER.USER_ID) AS USERS
FROM USER_INFO AS USER
JOIN ONLINE_SALE AS SALE
    ON USER.USER_ID = SALE.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE),
         MONTH(SALES_DATE),
         GENDER
ORDER BY YEAR(SALES_DATE),
         MONTH(SALES_DATE),
         GENDER
