SELECT COUNT(INFO.ID) AS FISH_COUNT, -- ID의 개수
       NAME.FISH_NAME -- 이름
FROM FISH_INFO AS INFO
JOIN FISH_NAME_INFO AS NAME -- FISH_TYPE으로 조인
    ON INFO.FISH_TYPE = NAME.FISH_TYPE
GROUP BY NAME.FISH_NAME
ORDER BY FISH_COUNT DESC -- 잡은 개수로 내림차순