WITH STATE AS (SELECT CAR_ID
               FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
               WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE) --  2022년 10월 16일 대여중인 차

SELECT CARS.CAR_ID,
       CASE 
            WHEN S.CAR_ID IS NOT NULL 
            THEN '대여중'
            ELSE '대여 가능'
       END AS AVAILABILITY
FROM (SELECT DISTINCT CAR_ID
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) AS CARS
LEFT JOIN STATE AS S
ON CARS.CAR_ID = S.CAR_ID
ORDER BY CARS.CAR_ID DESC
