SELECT ORD.PRODUCT_ID,
       PRO.PRODUCT_NAME,
       PRICE * SUM(AMOUNT) AS TOTAL_SALES
FROM FOOD_ORDER AS ORD
JOIN FOOD_PRODUCT AS PRO
    ON ORD.PRODUCT_ID = PRO.PRODUCT_ID
WHERE MONTH(PRODUCE_DATE) = '5'
GROUP BY ORD.PRODUCT_ID
ORDER BY PRICE * SUM(AMOUNT) DESC,
         ORD.PRODUCT_ID