SELECT ORD.PRODUCT_ID,
       PRO.PRODUCT_NAME,
       PRICE * SUM(AMOUNT) AS TOTAL_SALES -- 제품 가격과 총 주문량을 곱하여 총 매출
FROM FOOD_ORDER AS ORD
JOIN FOOD_PRODUCT AS PRO
    ON ORD.PRODUCT_ID = PRO.PRODUCT_ID
WHERE MONTH(PRODUCE_DATE) = '5' -- 5월에 주문한 것만
GROUP BY ORD.PRODUCT_ID -- 주문 번호가 달라도 식품 ID로 그룹화하여 총 주문량을 확인할 수 있게
ORDER BY PRICE * SUM(AMOUNT) DESC, -- 총 매출 기준 내림차순
         ORD.PRODUCT_ID -- 식품 ID기준 오름차순