SELECT HALF.FLAVOR
FROM FIRST_HALF AS HALF
JOIN (SELECT SHIPMENT_ID,
             FLAVOR,
             SUM(TOTAL_ORDER) AS TOTAL_ORDER
      FROM JULY
      GROUP BY FLAVOR) AS JULY
    ON HALF.SHIPMENT_ID = JULY.SHIPMENT_ID
GROUP BY HALF.FLAVOR
ORDER BY SUM(HALF.TOTAL_ORDER + JULY.TOTAL_ORDER) DESC
LIMIT 3


