WITH RV_CNT AS (SELECT MEMBER_ID,
                       COUNT(MEMBER_ID) AS CNT,
                       RANK() OVER(ORDER BY COUNT(MEMBER_ID) DESC ) AS RANKS
                FROM REST_REVIEW
                GROUP BY MEMBER_ID
                ORDER BY COUNT(MEMBER_ID) DESC)

SELECT PRO.MEMBER_NAME,
       REV.REVIEW_TEXT,
       DATE_FORMAT(REV.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW AS REV
JOIN MEMBER_PROFILE AS PRO
  ON REV.MEMBER_ID = PRO.MEMBER_ID
WHERE REV.MEMBER_ID IN (SELECT MEMBER_ID
                        FROM RV_CNT
                        WHERE RANKS = 1)
ORDER BY REVIEW_DATE,
         REVIEW_TEXT