SELECT INFO.ITEM_ID,
       INFO.ITEM_NAME,
       INFO.RARITY
FROM ITEM_INFO AS INFO
-- INFO 와 TREE 를 조인해서 ITEM_ID에 PARENT_ITEM_ID를 붙인다
INNER JOIN ITEM_TREE AS TREE
    ON INFO.ITEM_ID = TREE.ITEM_ID
-- TREE의 PARENT_ITEM_ID 가 INFO 테이블에서 RARITY가 RARE 인 아이템들만 뽑은 결과에 있는지를 조건으로 설정
WHERE TREE.PARENT_ITEM_ID IN (SELECT ITEM_ID
                              FROM ITEM_INFO
                              WHERE RARITY = 'RARE')
ORDER BY INFO.ITEM_ID DESC -- ITEM_ID 기준 내림차순