SELECT COUNT(*) AS FISH_COUNT -- 조건에 맞는 것만 COUNT
FROM FISH_INFO AS INFO
INNER JOIN FISH_NAME_INFO AS NAME -- 외래키인 FISH_TYPE으로 조인
    ON INFO.FISH_TYPE = NAME.FISH_TYPE
WHERE FISH_NAME = 'BASS' -- FISH_NAME 이 BASS 또는 SNAPPER 인 것만
    OR FISH_NAME = 'SNAPPER'