-- 코드를 입력하세요
SELECT FIRST.FLAVOR
FROM FIRST_HALF AS FIRST
INNER JOIN ICECREAM_INFO AS INFO -- 외래키 FLAVOR을 이용해 INNER JOIN
    ON FIRST.FLAVOR = INFO.FLAVOR
WHERE FIRST.TOTAL_ORDER > 3000 -- 상반기 주문 정보에서 3000보다 높은 것
    AND INFO.INGREDIENT_TYPE = 'fruit_based' -- 그리고 성분이 과일
ORDER BY FIRST.TOTAL_ORDER DESC