SELECT INFO.ID,
       NAME.FISH_NAME,
       INFO.LENGTH
FROM FISH_INFO AS INFO
JOIN FISH_NAME_INFO AS NAME -- FISH_TYPE을 외래키로 JOIN
    ON INFO.FISH_TYPE = NAME.FISH_TYPE
WHERE LENGTH IN (SELECT MAX(LENGTH)
                 FROM FISH_INFO
                 GROUP BY FISH_TYPE
                 HAVING FISH_TYPE = INFO.FISH_TYPE)
ORDER BY INFO.ID