SELECT INFO.INGREDIENT_TYPE, -- 아이스크림 정보의 타입
       SUM(TOTAL_ORDER) AS TOTAL_ORDER -- 그룹화된 TYPE의 TOTAL_ORDER 
FROM FIRST_HALF AS HALF
    INNER JOIN ICECREAM_INFO AS INFO
    ON HALF.FLAVOR = INFO.FLAVOR
GROUP BY INFO.INGREDIENT_TYPE -- 상반지 주문 + 아이스크림 정보 에서 INGREDIENT_TYPE으로 그룹화
ORDER BY TOTAL_ORDER -- TOTAL_ORDER 로 내림차순