-- 코드를 입력하세요
SELECT BOARD.TITLE, -- BOARD 테이플의 TITLE (제목)
       BOARD.BOARD_ID, -- BOARD 테이블의 BOARD_ID (게시글 ID)
       REPLY.REPLY_ID, -- REPLY 테이블의 REPLY_ID (댓글 ID)
       REPLY.WRITER_ID, -- REPLY 테이블의 WRITER_ID (작성자 ID)
       REPLY.CONTENTS, -- REPLY 테이블의 CONTENTS (댓글 내용)
       -- MYSQL 날짜 포멧 설정 DATE_FORMAT (설정할 컬럼, 포멧)
       DATE_FORMAT(REPLY.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE-- REPLY 테이블의 작성일 
FROM USED_GOODS_BOARD AS BOARD -- USED_GOODS_BOARD 를 BOARD 라고 칭한다
INNER JOIN USED_GOODS_REPLY AS REPLY -- USED_GOODS_REPLY 를 REPLY 라고 칭한다
    ON BOARD.BOARD_ID = REPLY.BOARD_ID -- BOARD의 BOARD_ID 와 REPLY 의 BOARD_ID 를 키로 조인
WHERE MONTH(BOARD.CREATED_DATE) = '10'
ORDER BY REPLY.CREATED_DATE, BOARD.TITLE -- 댓글 작성일로 오름차순, 같다면 글 제목으로 오름차순