SELECT D.DEPT_ID,
       D.DEPT_NAME_EN,
       ROUND(AVG(SAL), 0) AS AVG_SAL -- ROUND -> 반올림, 반올림 해서 끝날 자리, AVG -> 평균
FROM HR_DEPARTMENT AS D
JOIN HR_EMPLOYEES AS E
    ON D.DEPT_ID = E.DEPT_ID
GROUP BY D.DEPT_ID
ORDER BY AVG(SAL) DESC